#!/bin/bash
for file in "$1"/*; do
    # Check if the item is a file
    if [ -f "$file" ]; then
        echo "File: $file"
        
        SIZE=$(du -sh "$file" | cut -f1)
        echo "Size: $SIZE"
        
        WORD_COUNT=$(wc -w < "$file")
        echo "Word Count: $WORD_COUNT"
    fi
done
